
import { faker } from "@faker-js/faker";
export default (user,count,projectIdIds) => {
    let data = [];
    for (let i = 0; i < count; i++) {
        const fake = {
projectId: projectIdIds[i % projectIdIds.length],
themeName: faker.lorem.sentence(1),
bodyColor: faker.lorem.sentence(1),
emphasisColor: faker.lorem.sentence(1),
secondaryColor: faker.lorem.sentence(1),
tertiaryColor: faker.lorem.sentence(1),
codeColor: faker.lorem.sentence(1),
highlightColor: faker.lorem.sentence(1),
borderColorTranslucent: faker.lorem.sentence(1),
bodyBg: faker.lorem.sentence(1),
borderColor: faker.lorem.sentence(1),
highlightBg: faker.lorem.sentence(1),
secondaryBg: faker.lorem.sentence(1),
tertiaryBg: faker.lorem.sentence(1),
formInvalidBorderColor: faker.lorem.sentence(1),
formInvalidColor: faker.lorem.sentence(1),
formValidBorderColor: faker.lorem.sentence(1),
formValidColor: faker.lorem.sentence(1),
headingColor: faker.lorem.sentence(1),
linkColor: faker.lorem.sentence(1),
linkHoverColor: faker.lorem.sentence(1),
primary: faker.lorem.sentence(1),
primaryBgSubtle: faker.lorem.sentence(1),
primaryBorderSubtle: faker.lorem.sentence(1),
primaryTextEmphasis: faker.lorem.sentence(1),
secondary: faker.lorem.sentence(1),
secondaryBgSubtle: faker.lorem.sentence(1),
secondaryBorderSubtle: faker.lorem.sentence(1),
secondaryTextEmphasis: faker.lorem.sentence(1),
tertiary: faker.lorem.sentence(1),
tertiaryBgSubtle: faker.lorem.sentence(1),
tertiaryBorderSubtle: faker.lorem.sentence(1),
tertiaryTextEmphasis: faker.lorem.sentence(1),
success: faker.lorem.sentence(1),
successBgSubtle: faker.lorem.sentence(1),
successBorderSubtle: faker.lorem.sentence(1),
successTextEmphasis: faker.lorem.sentence(1),
info: faker.lorem.sentence(1),
infoBgSubtle: faker.lorem.sentence(1),
infoBorderSubtle: faker.lorem.sentence(1),
infoTextEmphasis: faker.lorem.sentence(1),
danger: faker.lorem.sentence(1),
dangerBgSubtle: faker.lorem.sentence(1),
dangerBorderSubtle: faker.lorem.sentence(1),
dangerTextEmphasis: faker.lorem.sentence(1),
warning: faker.lorem.sentence(1),
warningBgSubtle: faker.lorem.sentence(1),
warningBorderSubtle: faker.lorem.sentence(1),
warningTextEmphasis: faker.lorem.sentence(1),
dark: faker.lorem.sentence(1),
darkBgSubtle: faker.lorem.sentence(1),
darkBorderSubtle: faker.lorem.sentence(1),
darkTextEmphasis: faker.lorem.sentence(1),
bodyColorRgb: faker.lorem.sentence(1),
emphasisColorRgb: faker.lorem.sentence(1),
linkColorRgb: faker.lorem.sentence(1),
linkHoverColorRgb: faker.lorem.sentence(1),
tertiaryColorRgb: faker.lorem.sentence(1),
secondaryBgRgb: faker.lorem.sentence(1),
tertiaryBgRgb: faker.lorem.sentence(1),
lightBorderSubtle: faker.lorem.sentence(1),
lightTextEmphasis: faker.lorem.sentence(1),
isDefault: faker.lorem.sentence(1),

updatedBy: user._id,
createdBy: user._id
        };
        data = [...data, fake];
    }
    return data;
};
